### ISSUE TITLE
Discussion about permissions

### ISSUE THREAD

**Issue by OliviaLynn** [lincc-frameworks/lf-workflow-dash#24]
I was surprised to see I can't merge a change to fix the problem in our run_update workflow ([see here](https://github.com/lincc-frameworks/lf-workflow-dash/actions/runs/7310446545/job/19919070753)) with the fix now waiting in #23, and [tested out in a fork ](https://github.com/OliviaLynn/lf-workflow-dash-fork/actions/runs/7310519877)to make sure it will make the change as intended.

 It would be beneficial to allow developers to add hotfixes like these outside of the usual PR cycle. (Making a fork is a little tedious, and I don't know if I'd remember to go back and check things indeed worked if I waited for the end of a review.)

As an internal tool, I believe we should be able to trust people to use their best judgement. When the project gets more stable we could revisit restricting it completely?

**Comment by delucchi-cmu** [comment]
I'd advocate for continuing to have branch protection for all shared projects.

There are some process work-arounds that might be beneficial:
- everyone on the team can create branches, so shouldn't need to create forked repos for each change
- adding reviewers from self-selected list of people-who-are-happy-to-review. 
  - The Eeny slack bot can help
  - the lincc-frameworks/reviewers team in this github organization can auto-select a reviewer
- be aggressive when asking for a review, and don't be shy about nagging if a review is taking too long
- Use auto-merge on small PRs so they can be merged immediately after getting all of the necessary approvals

Some of these (branch creation permissions, auto-merge functionality) need to be enabled on a per-repo basis, so if you notice any repos where these actions aren't possible, please escalate.

**Comment by OliviaLynn** [comment]
Following up our in-person discussion: despite branches not providing all the features of forks in a gihub acitons/github pages oriented repo like this, we ruled in favor of branch protection. Furthermore, I am not to feel like any PR is too small/naggy and should feel free to make them and add Melissa as a reviewer freely. For example, even a one-liner like 23, and even if it were still just experimental (ie, if I had wanted to merge it without checking on a fork that it would work).
