### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by OliviaLynn** [lincc-frameworks/lf-workflow-dash#5]
At this point it might be nice to move the favicon, stylesheet, etc to their own dir(s), maybe quarantine the rail files out to reduce clutter. 

Also a good time to think about names of files (and maybe the overall project name - I'm not 100% sold on it)

**Comment by delucchi-cmu** [comment]
Closed by https://github.com/lincc-frameworks/lf-workflow-dash/pull/17
